
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ZHSM.cfg
{
public sealed partial class BossCfg : Luban.BeanBase
{
    public BossCfg(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["BulletAssetPath"].IsString) { throw new SerializationException(); }  BulletAssetPath = _buf["BulletAssetPath"]; }
    }

    public static BossCfg DeserializeBossCfg(JSONNode _buf)
    {
        return new BossCfg(_buf);
    }

    /// <summary>
    /// Boss编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 子弹资源路径
    /// </summary>
    public readonly string BulletAssetPath;
   
    public const int __ID__ = 1733235095;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "BulletAssetPath:" + BulletAssetPath + ","
        + "}";
    }
}

}

