
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ZHSM.cfg
{
public sealed partial class CharacterCfg : Luban.BeanBase
{
    public CharacterCfg(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["EntityId"].IsNumber) { throw new SerializationException(); }  EntityId = _buf["EntityId"]; }
        { if(!_buf["DisplayName"].IsString) { throw new SerializationException(); }  DisplayName = _buf["DisplayName"]; }
        { if(!_buf["HP"].IsNumber) { throw new SerializationException(); }  HP = _buf["HP"]; }
    }

    public static CharacterCfg DeserializeCharacterCfg(JSONNode _buf)
    {
        return new CharacterCfg(_buf);
    }

    /// <summary>
    /// 实体编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 实体ID
    /// </summary>
    public readonly int EntityId;
    /// <summary>
    /// 角色名称
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// 角色血量
    /// </summary>
    public readonly int HP;
   
    public const int __ID__ = -1278909285;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "EntityId:" + EntityId + ","
        + "DisplayName:" + DisplayName + ","
        + "HP:" + HP + ","
        + "}";
    }
}

}

