
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ZHSM.cfg
{
public sealed partial class ConfigCfg : Luban.BeanBase
{
    public ConfigCfg(JSONNode _buf) 
    {
        { if(!_buf["Key"].IsString) { throw new SerializationException(); }  Key = _buf["Key"]; }
        { if(!_buf["Value"].IsString) { throw new SerializationException(); }  Value = _buf["Value"]; }
        { if(!_buf["Desc"].IsString) { throw new SerializationException(); }  Desc = _buf["Desc"]; }
    }

    public static ConfigCfg DeserializeConfigCfg(JSONNode _buf)
    {
        return new ConfigCfg(_buf);
    }

    /// <summary>
    /// 语言ID
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 中国语
    /// </summary>
    public readonly string Value;
    /// <summary>
    /// !预留备注
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = 1199490466;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Key:" + Key + ","
        + "Value:" + Value + ","
        + "Desc:" + Desc + ","
        + "}";
    }
}

}

