
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ZHSM.cfg
{ 
    public enum EnemyType
    {
        /// <summary>
        /// 未知
        /// </summary>
        Unknow = 0,
        /// <summary>
        /// 待机、攻击会被打断
        /// </summary>
        Normal = 1,
        /// <summary>
        /// 攻击会被打断、同时闪避
        /// </summary>
        Elite = 2,
        /// <summary>
        /// 硬抗伤害
        /// </summary>
        Boss = 3,
    }

} 

