
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ZHSM.cfg
{
public sealed partial class LevelWaveEnemy : Luban.BeanBase
{
    public LevelWaveEnemy(JSONNode _buf) 
    {
        { if(!_buf["enemyId"].IsNumber) { throw new SerializationException(); }  EnemyId = _buf["enemyId"]; }
        { if(!_buf["count"].IsNumber) { throw new SerializationException(); }  Count = _buf["count"]; }
        { if(!_buf["probability"].IsNumber) { throw new SerializationException(); }  Probability = _buf["probability"]; }
    }

    public static LevelWaveEnemy DeserializeLevelWaveEnemy(JSONNode _buf)
    {
        return new LevelWaveEnemy(_buf);
    }

    /// <summary>
    /// 小怪ID
    /// </summary>
    public readonly int EnemyId;
    /// <summary>
    /// 刷新数量
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 刷新权重
    /// </summary>
    public readonly float Probability;
   
    public const int __ID__ = 1387152651;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "enemyId:" + EnemyId + ","
        + "count:" + Count + ","
        + "probability:" + Probability + ","
        + "}";
    }
}

}

