
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ZHSM.cfg
{
public sealed partial class PortalConfig : Luban.BeanBase
{
    public PortalConfig(JSONNode _buf) 
    {
        { if(!_buf["position"].IsObject) { throw new SerializationException(); }  Position = Position.DeserializePosition(_buf["position"]);  }
        { if(!_buf["rotation"].IsObject) { throw new SerializationException(); }  Rotation = Rotation.DeserializeRotation(_buf["rotation"]);  }
        { if(!_buf["nextLevelId"].IsNumber) { throw new SerializationException(); }  NextLevelId = _buf["nextLevelId"]; }
    }

    public static PortalConfig DeserializePortalConfig(JSONNode _buf)
    {
        return new PortalConfig(_buf);
    }

    /// <summary>
    /// 坐标
    /// </summary>
    public readonly Position Position;
    /// <summary>
    /// 旋转
    /// </summary>
    public readonly Rotation Rotation;
    /// <summary>
    /// 目标关卡ID
    /// </summary>
    public readonly int NextLevelId;
   
    public const int __ID__ = 343624430;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Position?.ResolveRef(tables);
        Rotation?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "position:" + Position + ","
        + "rotation:" + Rotation + ","
        + "nextLevelId:" + NextLevelId + ","
        + "}";
    }
}

}

