
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ZHSM.cfg
{
public sealed partial class PositionAndRotation : Luban.BeanBase
{
    public PositionAndRotation(JSONNode _buf) 
    {
        { if(!_buf["position"].IsObject) { throw new SerializationException(); }  Position = Position.DeserializePosition(_buf["position"]);  }
        { if(!_buf["rotation"].IsObject) { throw new SerializationException(); }  Rotation = Rotation.DeserializeRotation(_buf["rotation"]);  }
    }

    public static PositionAndRotation DeserializePositionAndRotation(JSONNode _buf)
    {
        return new PositionAndRotation(_buf);
    }

    public readonly Position Position;
    public readonly Rotation Rotation;
   
    public const int __ID__ = 133814636;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Position?.ResolveRef(tables);
        Rotation?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "position:" + Position + ","
        + "rotation:" + Rotation + ","
        + "}";
    }
}

}

