
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading.Tasks;
using Luban;
using SimpleJSON;

namespace ZHSM.cfg
{
public partial class Tables : BaseLubanTables
{
    public TbEntityCfg TbEntityCfg {get; private set;}
    public TbMusicCfg TbMusicCfg {get; private set;}
    public TbSceneCfg TbSceneCfg {get; private set;}
    public TbSoundCfg TbSoundCfg {get; private set;}
    public TbUIFormCfg TbUIFormCfg {get; private set;}
    public TbUISoundCfg TbUISoundCfg {get; private set;}
    public TbConfigCfg TbConfigCfg {get; private set;}
    public TbCharacterCfg TbCharacterCfg {get; private set;}
    public TbEnemyCfg TbEnemyCfg {get; private set;}
    public TbWeaponCfg TbWeaponCfg {get; private set;}
    public TbLevelsCfg TbLevelsCfg {get; private set;}

    public Tables() { }

    public override LubanTableType GetTableType
    {
        get { return LubanTableType.JSON; }
    }

    public override async Task LoadAsync(System.Func<string, Task<JSONNode>> loader)
    {
        TbEntityCfg = new TbEntityCfg(await loader("tbentitycfg"));
        TbMusicCfg = new TbMusicCfg(await loader("tbmusiccfg"));
        TbSceneCfg = new TbSceneCfg(await loader("tbscenecfg"));
        TbSoundCfg = new TbSoundCfg(await loader("tbsoundcfg"));
        TbUIFormCfg = new TbUIFormCfg(await loader("tbuiformcfg"));
        TbUISoundCfg = new TbUISoundCfg(await loader("tbuisoundcfg"));
        TbConfigCfg = new TbConfigCfg(await loader("tbconfigcfg"));
        TbCharacterCfg = new TbCharacterCfg(await loader("tbcharactercfg"));
        TbEnemyCfg = new TbEnemyCfg(await loader("tbenemycfg"));
        TbWeaponCfg = new TbWeaponCfg(await loader("tbweaponcfg"));
        TbLevelsCfg = new TbLevelsCfg(await loader("tblevelscfg"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbEntityCfg.ResolveRef(this);
        TbMusicCfg.ResolveRef(this);
        TbSceneCfg.ResolveRef(this);
        TbSoundCfg.ResolveRef(this);
        TbUIFormCfg.ResolveRef(this);
        TbUISoundCfg.ResolveRef(this);
        TbConfigCfg.ResolveRef(this);
        TbCharacterCfg.ResolveRef(this);
        TbEnemyCfg.ResolveRef(this);
        TbWeaponCfg.ResolveRef(this);
        TbLevelsCfg.ResolveRef(this);
    }
}

}
