
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ZHSM.cfg
{
public partial class TbBossCfg
{
    private readonly System.Collections.Generic.Dictionary<int, BossCfg> _dataMap;
    private readonly System.Collections.Generic.List<BossCfg> _dataList;
    
    public TbBossCfg(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BossCfg>();
        _dataList = new System.Collections.Generic.List<BossCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BossCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = BossCfg.DeserializeBossCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BossCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<BossCfg> DataList => _dataList;

    public BossCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BossCfg Get(int key) => _dataMap[key];
    public BossCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

