
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ZHSM.cfg
{
public partial class TbCharacterCfg
{
    private readonly System.Collections.Generic.Dictionary<int, CharacterCfg> _dataMap;
    private readonly System.Collections.Generic.List<CharacterCfg> _dataList;
    
    public TbCharacterCfg(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CharacterCfg>();
        _dataList = new System.Collections.Generic.List<CharacterCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CharacterCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = CharacterCfg.DeserializeCharacterCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CharacterCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<CharacterCfg> DataList => _dataList;

    public CharacterCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CharacterCfg Get(int key) => _dataMap[key];
    public CharacterCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

