
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ZHSM.cfg
{
public partial class TbConfigCfg
{
    private readonly System.Collections.Generic.Dictionary<string, ConfigCfg> _dataMap;
    private readonly System.Collections.Generic.List<ConfigCfg> _dataList;
    
    public TbConfigCfg(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, ConfigCfg>();
        _dataList = new System.Collections.Generic.List<ConfigCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ConfigCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = ConfigCfg.DeserializeConfigCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, ConfigCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<ConfigCfg> DataList => _dataList;

    public ConfigCfg GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ConfigCfg Get(string key) => _dataMap[key];
    public ConfigCfg this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

