
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ZHSM.cfg
{
public partial class TbEntityCfg
{
    private readonly System.Collections.Generic.Dictionary<int, EntityCfg> _dataMap;
    private readonly System.Collections.Generic.List<EntityCfg> _dataList;
    
    public TbEntityCfg(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EntityCfg>();
        _dataList = new System.Collections.Generic.List<EntityCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            EntityCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = EntityCfg.DeserializeEntityCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EntityCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<EntityCfg> DataList => _dataList;

    public EntityCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EntityCfg Get(int key) => _dataMap[key];
    public EntityCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

