
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ZHSM.cfg
{
public partial class TbLevelsCfg
{
    private readonly System.Collections.Generic.Dictionary<int, LevelsCfg> _dataMap;
    private readonly System.Collections.Generic.List<LevelsCfg> _dataList;
    
    public TbLevelsCfg(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, LevelsCfg>();
        _dataList = new System.Collections.Generic.List<LevelsCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            LevelsCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = LevelsCfg.DeserializeLevelsCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, LevelsCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<LevelsCfg> DataList => _dataList;

    public LevelsCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public LevelsCfg Get(int key) => _dataMap[key];
    public LevelsCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

