
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ZHSM.cfg
{
public partial class TbSceneCfg
{
    private readonly System.Collections.Generic.Dictionary<int, SceneCfg> _dataMap;
    private readonly System.Collections.Generic.List<SceneCfg> _dataList;
    
    public TbSceneCfg(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SceneCfg>();
        _dataList = new System.Collections.Generic.List<SceneCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            SceneCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = SceneCfg.DeserializeSceneCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SceneCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<SceneCfg> DataList => _dataList;

    public SceneCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SceneCfg Get(int key) => _dataMap[key];
    public SceneCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

