
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ZHSM.cfg
{
public partial class TbSoundCfg
{
    private readonly System.Collections.Generic.Dictionary<int, SoundCfg> _dataMap;
    private readonly System.Collections.Generic.List<SoundCfg> _dataList;
    
    public TbSoundCfg(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SoundCfg>();
        _dataList = new System.Collections.Generic.List<SoundCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            SoundCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = SoundCfg.DeserializeSoundCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SoundCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<SoundCfg> DataList => _dataList;

    public SoundCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SoundCfg Get(int key) => _dataMap[key];
    public SoundCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

