
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ZHSM.cfg
{
public partial class TbUISoundCfg
{
    private readonly System.Collections.Generic.Dictionary<int, UISoundCfg> _dataMap;
    private readonly System.Collections.Generic.List<UISoundCfg> _dataList;
    
    public TbUISoundCfg(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, UISoundCfg>();
        _dataList = new System.Collections.Generic.List<UISoundCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            UISoundCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = UISoundCfg.DeserializeUISoundCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, UISoundCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<UISoundCfg> DataList => _dataList;

    public UISoundCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UISoundCfg Get(int key) => _dataMap[key];
    public UISoundCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

