
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ZHSM.cfg
{
public partial class TbUIFormCfg
{
    private readonly System.Collections.Generic.Dictionary<int, UIFormCfg> _dataMap;
    private readonly System.Collections.Generic.List<UIFormCfg> _dataList;
    
    public TbUIFormCfg(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, UIFormCfg>();
        _dataList = new System.Collections.Generic.List<UIFormCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            UIFormCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = UIFormCfg.DeserializeUIFormCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, UIFormCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<UIFormCfg> DataList => _dataList;

    public UIFormCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UIFormCfg Get(int key) => _dataMap[key];
    public UIFormCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

