
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ZHSM.cfg
{
public partial class TbWeaponGroupCfg
{
    private readonly System.Collections.Generic.Dictionary<int, WeaponGroupCfg> _dataMap;
    private readonly System.Collections.Generic.List<WeaponGroupCfg> _dataList;
    
    public TbWeaponGroupCfg(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WeaponGroupCfg>();
        _dataList = new System.Collections.Generic.List<WeaponGroupCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            WeaponGroupCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = WeaponGroupCfg.DeserializeWeaponGroupCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, WeaponGroupCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<WeaponGroupCfg> DataList => _dataList;

    public WeaponGroupCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WeaponGroupCfg Get(int key) => _dataMap[key];
    public WeaponGroupCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

