
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ZHSM.cfg
{
public partial class TbWeaponCfg
{
    private readonly System.Collections.Generic.Dictionary<int, WeaponCfg> _dataMap;
    private readonly System.Collections.Generic.List<WeaponCfg> _dataList;
    
    public TbWeaponCfg(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WeaponCfg>();
        _dataList = new System.Collections.Generic.List<WeaponCfg>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            WeaponCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = WeaponCfg.DeserializeWeaponCfg(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, WeaponCfg> DataMap => _dataMap;
    public System.Collections.Generic.List<WeaponCfg> DataList => _dataList;

    public WeaponCfg GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WeaponCfg Get(int key) => _dataMap[key];
    public WeaponCfg this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

