
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ZHSM.cfg
{
public sealed partial class WeaponGroupCfg : Luban.BeanBase
{
    public WeaponGroupCfg(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["LeftWeaponId"].IsNumber) { throw new SerializationException(); }  LeftWeaponId = _buf["LeftWeaponId"]; }
        { if(!_buf["RightWeaponId"].IsNumber) { throw new SerializationException(); }  RightWeaponId = _buf["RightWeaponId"]; }
        { if(!_buf["Description"].IsString) { throw new SerializationException(); }  Description = _buf["Description"]; }
    }

    public static WeaponGroupCfg DeserializeWeaponGroupCfg(JSONNode _buf)
    {
        return new WeaponGroupCfg(_buf);
    }

    /// <summary>
    /// 武器组套装ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 套装名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 左手武器ID
    /// </summary>
    public readonly int LeftWeaponId;
    /// <summary>
    /// 右手武器ID
    /// </summary>
    public readonly int RightWeaponId;
    /// <summary>
    /// 套装描述
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = -1380506687;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "LeftWeaponId:" + LeftWeaponId + ","
        + "RightWeaponId:" + RightWeaponId + ","
        + "Description:" + Description + ","
        + "}";
    }
}

}

