
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace ZHSM.cfg
{
public sealed partial class WeaponCfg : Luban.BeanBase
{
    public WeaponCfg(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["EntityId"].IsNumber) { throw new SerializationException(); }  EntityId = _buf["EntityId"]; }
        { if(!_buf["BulletId"].IsNumber) { throw new SerializationException(); }  BulletId = _buf["BulletId"]; }
        { if(!_buf["FirePoint"].IsString) { throw new SerializationException(); }  FirePoint = _buf["FirePoint"]; }
        { if(!_buf["FlashEffectId"].IsNumber) { throw new SerializationException(); }  FlashEffectId = _buf["FlashEffectId"]; }
        { if(!_buf["HitEffectId"].IsNumber) { throw new SerializationException(); }  HitEffectId = _buf["HitEffectId"]; }
        { var __json0 = _buf["FireSounds"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; FireSounds = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  FireSounds[__index0++] = __v0; }   }
        { var __json0 = _buf["HitSounds"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; HitSounds = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  HitSounds[__index0++] = __v0; }   }
        { if(!_buf["Damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["Damage"]; }
        { if(!_buf["KnockUp"].IsNumber) { throw new SerializationException(); }  KnockUp = _buf["KnockUp"]; }
        { if(!_buf["Time"].IsNumber) { throw new SerializationException(); }  Time = _buf["Time"]; }
        { if(!_buf["TickDamage"].IsNumber) { throw new SerializationException(); }  TickDamage = _buf["TickDamage"]; }
        { if(!_buf["AttackDistance"].IsNumber) { throw new SerializationException(); }  AttackDistance = _buf["AttackDistance"]; }
    }

    public static WeaponCfg DeserializeWeaponCfg(JSONNode _buf)
    {
        return new WeaponCfg(_buf);
    }

    /// <summary>
    /// 武器编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 实体ID
    /// </summary>
    public readonly int EntityId;
    /// <summary>
    /// 子弹实体ID
    /// </summary>
    public readonly int BulletId;
    /// <summary>
    /// 发射点路径
    /// </summary>
    public readonly string FirePoint;
    /// <summary>
    /// 枪火特效ID
    /// </summary>
    public readonly int FlashEffectId;
    /// <summary>
    /// 子弹碰撞特效
    /// </summary>
    public readonly int HitEffectId;
    /// <summary>
    /// 开火音效
    /// </summary>
    public readonly int[] FireSounds;
    /// <summary>
    /// 子弹碰撞音效
    /// </summary>
    public readonly int[] HitSounds;
    /// <summary>
    /// 伤害值
    /// </summary>
    public readonly int Damage;
    /// <summary>
    /// 击飞力度
    /// </summary>
    public readonly float KnockUp;
    /// <summary>
    /// 持续时间
    /// </summary>
    public readonly int Time;
    /// <summary>
    /// 持续伤害
    /// </summary>
    public readonly int TickDamage;
    /// <summary>
    /// 攻击距离
    /// </summary>
    public readonly float AttackDistance;
   
    public const int __ID__ = 801300616;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "EntityId:" + EntityId + ","
        + "BulletId:" + BulletId + ","
        + "FirePoint:" + FirePoint + ","
        + "FlashEffectId:" + FlashEffectId + ","
        + "HitEffectId:" + HitEffectId + ","
        + "FireSounds:" + Luban.StringUtil.CollectionToString(FireSounds) + ","
        + "HitSounds:" + Luban.StringUtil.CollectionToString(HitSounds) + ","
        + "Damage:" + Damage + ","
        + "KnockUp:" + KnockUp + ","
        + "Time:" + Time + ","
        + "TickDamage:" + TickDamage + ","
        + "AttackDistance:" + AttackDistance + ","
        + "}";
    }
}

}

